<?php
session_start();
$castSize = $_POST['castSize'];
$castObject = [];
//print_r2($_POST);
for($i = 0; $i < $castSize; $i++){
    $r = strval(rand(0, 255));
    $g = strval(rand(0, 255));
    $b = strval(rand(0, 255));
    $tempObject->name = htmlspecialchars($_POST["castName" . $i]);
    $tempObject->nick = ((array_key_exists("castNick" . $i, $_POST)) ? htmlspecialchars($_POST["castNick" . $i]) : $tempObject->name);
    $tempObject->gender = $_POST["castGender" . $i];
    $tempObject->disposition = $_POST["castDisposition" . $i];
    $tempObject->strength = ((array_key_exists("castStrength" . $i, $_POST)) ? (int) $_POST["castStrength" . $i] : 5);
    $tempObject->health = ((array_key_exists("castHealth" . $i, $_POST)) ? (int) $_POST["castHealth" . $i] : 5);
    $tempObject->maxStrength = $tempObject->strength;
    $tempObject->modifiedStrength = $tempObject->strength / 5;
    $tempObject->dexterity = ((array_key_exists("castDex" . $i, $_POST)) ? (int) $_POST["castDex" . $i] : 5);
    $tempObject->intelligence = ((array_key_exists("castInt" . $i, $_POST)) ? (int) $_POST["castInt" . $i] : 5);
    $tempObject->charisma = ((array_key_exists("castCha" . $i, $_POST)) ? (int) $_POST["castCha" . $i] : 5);
    $tempObject->defense = 0;
    $tempObject->image = ((array_key_exists("castImage" . $i, $_POST)) ? $_POST["castImage" . $i] : "generateImage.php?imageInitial=" . substr(htmlspecialchars($_POST["castName" . $i]),0,1) . "&r=" . $r . "&g=" . $g . "&b=" . $b);
    $tempObject->status = "Alive";
    $tempObject->actionTaken = "false";
    $tempObject->daysOfFood = 1;
    $tempObject->daysWithoutFood = 0;
    $tempObject->daysOfWater = 1;
    $tempObject->desiredItems = [];
    $tempObject->inventory = [];
    $tempObject->arrows = 0;
    $tempObject->explosivesPlanted = 0;
    $tempObject->memberOfAlliance = -1;
    $tempObject->equippedItem = "";
    $tempObject->kills = 0;
    $tempObject->daysAlive = 0;
    $tempObject->orderMarker = $i;
    $tempObject->place = 0;
    array_push($castObject,clone $tempObject);
}
$_SESSION['castObject'] = json_encode($castObject);